// src/App.tsx
import React, { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import type { Book as BookType } from "./components/BookSlice";
import {
  fetchBooks,
  addBook,
  updateBook,
  deleteBook,
} from "./components/BookSlice";
import type { RootState, AppDispatch } from "./store";

import BookForm from "./components/BookForm";
import BookList from "./components/BookList";
import BookSearchSortFilter from "./components/BookSearchSortFilter";
import { Button } from "@mui/material";

const App: React.FC = () => {
  const dispatch = useDispatch<AppDispatch>();
  const books = useSelector((s: RootState) => s.books.items);
  const loading = useSelector((s: RootState) => s.books.loading);
  const error = useSelector((s: RootState) => s.books.error);

  const [openForm, setOpenForm] = useState(false);
  const [editing, setEditing] = useState<Partial<BookType> | undefined>();

  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("all");
  const [sortBy, setSortBy] = useState<"title" | "year">("title");
  const [sortDir, setSortDir] = useState<"asc" | "desc">("asc");

  useEffect(() => {
    dispatch(fetchBooks());
  }, [dispatch]);

  const categories = useMemo(
    () => Array.from(new Set(books.map((b) => b.category))).sort(),
    [books]
  );

  // Validation helper
  const isTitleDuplicate = (title: string, idToIgnore?: string) => {
    return books.some(
      (b) =>
        b.title.trim().toLowerCase() === title.trim().toLowerCase() &&
        b.id !== idToIgnore
    );
  };

  const handleSubmit = async (data: {
    id?: string;
    title: string;
    author: string;
    year: number;
    category: string;
  }) => {
    // client-side validate
    if (!data.title.trim()) {
      window.alert("Tên sách không được để trống");
      return;
    }
    if (isTitleDuplicate(data.title, data.id)) {
      window.alert("Tên sách không được trùng");
      return;
    }
    if (!data.author.trim()) {
      window.alert("Tên tác giả không được để trống");
      return;
    }
    if (
      data.year === null ||
      data.year === undefined ||
      Number.isNaN(data.year)
    ) {
      window.alert("Năm xuất bản không được bỏ trống");
      return;
    }
    if (Number(data.year) < 0) {
      window.alert("Năm xuất bản không được nhỏ hơn 0");
      return;
    }
    if (!data.category.trim()) {
      window.alert("Tên thể loại không được để trống");
      return;
    }

    if (data.id) {
      // update
      await dispatch(updateBook({ ...(data as BookType) }));
    } else {
      // add -> ensure id generated by server or use Date.now if server needs
      await dispatch(
        addBook({
          title: data.title,
          author: data.author,
          year: data.year,
          category: data.category,
        })
      );
    }

    setOpenForm(false);
    setEditing(undefined);
  };

  const filteredSorted = useMemo(() => {
    let out = books.slice();
    if (search.trim()) {
      const q = search.toLowerCase();
      out = out.filter(
        (b) =>
          b.title.toLowerCase().includes(q) ||
          b.author.toLowerCase().includes(q)
      );
    }
    if (category !== "all") out = out.filter((b) => b.category === category);

    out.sort((a, b) => {
      if (sortBy === "title") {
        const r = a.title.localeCompare(b.title);
        return sortDir === "asc" ? r : -r;
      } else {
        const r = a.year - b.year;
        return sortDir === "asc" ? r : -r;
      }
    });
    return out;
  }, [books, search, category, sortBy, sortDir]);

  return (
    <div className="max-w-4xl mx-auto p-6 bg-gray-50 min-h-screen">
      <h1 className="text-3xl font-bold mb-6">📚 Book Library Manager</h1>

      <Button
        variant="contained"
        onClick={() => {
          setEditing(undefined);
          setOpenForm(true);
        }}
      >
        Add Book
      </Button>

      <div className="mt-4">
        <BookSearchSortFilter
          search={search}
          category={category}
          sortBy={sortBy}
          sortDir={sortDir}
          categories={categories}
          onSearchChange={setSearch}
          onCategoryChange={setCategory}
          onSortChange={(by, dir) => {
            setSortBy(by);
            setSortDir(dir);
          }}
          onClear={() => {
            setSearch("");
            setCategory("all");
            setSortBy("title");
            setSortDir("asc");
          }}
        />
      </div>

      <div className="mt-6">
        {loading && <div>Loading...</div>}
        {error && <div className="text-red-600">Error: {error}</div>}

        <BookList
          books={filteredSorted}
          onEdit={(b) => {
            setEditing(b);
            setOpenForm(true);
          }}
          onDelete={(id) => {
            const ok = window.confirm("Bạn có chắc muốn xóa quyển sách này?");
            if (ok) dispatch(deleteBook(id));
          }}
        />
      </div>

      <BookForm
        open={openForm}
        initial={editing}
        onClose={() => {
          setOpenForm(false);
          setEditing(undefined);
        }}
        onSubmit={handleSubmit}
      />
    </div>
  );
};

export default App;
